/* tslint:disable */
/* eslint-disable */
/**
 * Patient Management Api
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your-email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 *
 * @export
 * @interface EmergencyContact
 */
export interface EmergencyContact {
  /**
   * Name of emergency contact
   * @type {string}
   * @memberof EmergencyContact
   */
  name?: string;
  /**
   * Relationship to patient
   * @type {string}
   * @memberof EmergencyContact
   */
  relationship?: string;
  /**
   * Phone number of emergency contact
   * @type {string}
   * @memberof EmergencyContact
   */
  phoneNumber?: string;
}

/**
 * Check if a given object implements the EmergencyContact interface.
 */
export function instanceOfEmergencyContact(): boolean {
  let isInstance = true;

  return isInstance;
}

export function EmergencyContactFromJSON(json: any): EmergencyContact {
  return EmergencyContactFromJSONTyped(json);
}

export function EmergencyContactFromJSONTyped(json: any): EmergencyContact {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    relationship: !exists(json, 'relationship') ? undefined : json['relationship'],
    phoneNumber: !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
  };
}

export function EmergencyContactToJSON(value?: EmergencyContact | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    relationship: value.relationship,
    phoneNumber: value.phoneNumber,
  };
}
