/* tslint:disable */
/* eslint-disable */
/**
 * Patient Management Api
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your-email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 *
 * @export
 * @interface Medication
 */
export interface Medication {
  /**
   * Name of the medication
   * @type {string}
   * @memberof Medication
   */
  name?: string;
  /**
   * Dosage amount
   * @type {string}
   * @memberof Medication
   */
  dosage?: string;
  /**
   * How often to take the medication
   * @type {string}
   * @memberof Medication
   */
  frequency?: string;
  /**
   * Duration of treatment
   * @type {string}
   * @memberof Medication
   */
  duration?: string;
}

/**
 * Check if a given object implements the Medication interface.
 */
export function instanceOfMedication(): boolean {
  let isInstance = true;

  return isInstance;
}

export function MedicationFromJSON(json: any): Medication {
  return MedicationFromJSONTyped(json);
}

export function MedicationFromJSONTyped(json: any): Medication {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    dosage: !exists(json, 'dosage') ? undefined : json['dosage'],
    frequency: !exists(json, 'frequency') ? undefined : json['frequency'],
    duration: !exists(json, 'duration') ? undefined : json['duration'],
  };
}

export function MedicationToJSON(value?: Medication | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    dosage: value.dosage,
    frequency: value.frequency,
    duration: value.duration,
  };
}
