/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SamsviMdmPatientList {
    }
}
declare global {
    interface HTMLSamsviMdmPatientListElement extends Components.SamsviMdmPatientList, HTMLStencilElement {
    }
    var HTMLSamsviMdmPatientListElement: {
        prototype: HTMLSamsviMdmPatientListElement;
        new (): HTMLSamsviMdmPatientListElement;
    };
    interface HTMLElementTagNameMap {
        "samsvi-mdm-patient-list": HTMLSamsviMdmPatientListElement;
    }
}
declare namespace LocalJSX {
    interface SamsviMdmPatientList {
    }
    interface IntrinsicElements {
        "samsvi-mdm-patient-list": SamsviMdmPatientList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "samsvi-mdm-patient-list": LocalJSX.SamsviMdmPatientList & JSXBase.HTMLAttributes<HTMLSamsviMdmPatientListElement>;
        }
    }
}
